### ISSUE TITLE
"Reverb Communications, Inc."

### ISSUE THREAD

**Issue by dguis** [D-Multi-cTech/cTechstudios.d-multi.com#4]
Why does the site say " Reverb Communications, Inc." at the bottom? Thanks!

<a href="https://github.com/dguis"><h6>Officially Written by dguis from D-Multi</h6><img src="https://dguis.github.io/RES/New%20Logos/DG50x50db.png"></a>

**Comment by dude2093350** [comment]
Publishers of World or War
